### ISSUE TITLE
[Request] Export/Import to csv

### ISSUE THREAD

**Issue by Endracion** [Fusion86/Cirilla#16]
Search function was already very helpful, but seeing as the format is similar to excel tables - would it be possible for you to make an import/export function that can deal with the encoding of these files?

I'm trying to update a bunch of files in different languages and it currently requires straight copy/pasting from one file to the other; it would save a huge amount of time to be able to open these in excel.

Thanks in advance if it's possible!

**Comment by Fusion86** [comment]
A bit late, but added an import/export feature in 520e0ac629e5b682c3da0113d8999c8be4e60913 in case anyone still needs it.
