### ISSUE TITLE
Not support for some languages

### ISSUE THREAD

**Issue by rockingdice** [Fusion86/Cirilla#6]
all texts are 'invalid message': ara,kor,cht,pol,ptb,rus

**Comment by rockingdice** [comment]
I think it's not the issue of your tool. The extracted .gmd files are incorrect.

**Comment by Fusion86** [comment]
q00263_kor.gmd etc open fine for me. I believe 'Invalid message' texts are just unused in-game, but I might be wrong.

**Comment by Fusion86** [comment]
While working on a different bug I noticed that some files indeed only have "Invalid Message" in them (e.g. action_trial_kor.gmd) and in fact all action_trial files in the languages you listed are 'invalid'.

**Comment by Fusion86** [comment]
Continuing this in https://github.com/mhvuze/WorldChunkTool/issues/3
