### ISSUE TITLE
Adding entries

### ISSUE THREAD

**Issue by mhvuze** [Fusion86/Cirilla#7]
Hey,

I haven't looked into your analysis of the GMD format yet but if you have enough understanding to add new entries, that would be much appreciated. In any case just leaving this here as a potential enhancement 💃 

Cheers

**Comment by Fusion86** [comment]
Added experimental support for this in b022e5b6efbf7f0ffc58ccd094e8de57ef9a2e22.
Haven't tested it in-game so there's a fair chance it doesn't work.

**Comment by mhvuze** [comment]
Thanks, on a superficial level it seems to work fine. The game loads and all original text is displayed properly, however the new entries are not tied to the newly created item in my case. Is there any chance AddString misses some count or size so the text is cut off/not processed? It might be a case of Capcom devs being weirdos however. I'll take a look later today.

**Comment by Fusion86** [comment]
Could you send a sample file that adds an item to the game, or explain how you did it?

I tried using your item editing tool but I couldn't find where to specify the item key name.

**Comment by mhvuze** [comment]
Because there is no way to do so in the itemData. My assumption was the game uses itemID to determine the gmd strings. So that Item ID 1000 simply pulls name 2001 and exp 2002 from the gmd.

I included my edited itemData and the item gmd. 

[common.zip](https://github.com/Fusion86/Cirilla/files/2363137/common.zip)

**Comment by Fusion86** [comment]
Added in b022e5b6efbf7f0ffc58ccd094e8de57ef9a2e22 and improved in bcb3818c035b0b67cdd1b951dff6912be5f51ad8.
